choco install -y `
    powershell-core `
    microsoft-windows-terminal `
    vscode `
    notepadplusplus `
    GoogleChrome `
    Firefox `
    Brave `
    Vivaldi `
    7zip `
    teamviewer `
    chrome-remote-desktop-chrome `
    chrome-remote-desktop-host `
    git `
    microsoft-teams `
    gitkraken `
    WinMerge `
    python `
    azure-cli `
    azurepowershell `
    WinRAR `
    spotify `
    snagit `
    IrfanView `
    LINE `
    Whatsapp `
    telegram `
    LINQPad `
    AdoptOpenJDK15 `
    AdoptOpenJDK15JRE `
    coretemp `
    discord `
    dotnetfx `
    Everything `
    f.lux `
    internet-download-manager `
    lastpass `
    nordvpn `
    qbittorrent `
    signal `
    steam `
    sysinternals `
    vlc `
    vmwareworkstation `
    AzureStorageExplorer `
    winrar `
    Audacity `
    Battle.net `
    CrystalDiskInfo `
    CrystalDiskMark `
    HWiNFO `
    IronPython `
    LatencyMon `
    NetBalancer `
    Notion `
    Origin `
    Shotcut `
    Slack `
    Uplay `
    Zoom `
    beyondcompare2 `
    beyondcompare-integration `
    beyondcompare `
    docker-desktop `
    golang `
    nodejs `    
    teracopy